[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/catalog"
  to = "/.netlify/functions/catalog"
  status = 200

[[redirects]]
  from = "/api/checkout"
  to = "/.netlify/functions/checkout"
  status = 200

[[redirects]]
  from = "/api/blog"
  to = "/.netlify/functions/blog"
  status = 200

[[redirects]]
  from = "/api/subscribe"
  to = "/.netlify/functions/subscribe"
  status = 200
